spring.application.name=bookings
server.port=8080

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5434/bookings}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

spring.rabbitmq.host=${RABBIT_HOST:localhost}
spring.rabbitmq.port=${RABBIT_PORT:5672}
spring.rabbitmq.username=${RABBIT_USER:guest}
spring.rabbitmq.password=${RABBIT_PASSWORD:guest}

jwt.secret=${JWT_SECRET:dev-secret-change-me-please-32chars}
